/**
 * 常见英文国家/地区全称、别名 → 简体中文（用于落地展示串补全，非 ASN）。
 * 键为小写，按长度降序替换。
 */
const EN_COUNTRY_OR_REGION_TO_ZH = [
  ["hong kong sar, china", "香港"],
  ["hong kong special administrative region", "香港"],
  ["hong kong sar", "香港"],
  ["hong kong", "香港"],
  ["united states of america", "美国"],
  ["united states", "美国"],
  ["u.s. virgin islands", "美属维尔京群岛"],
  ["u.s.", "美国"],
  ["usa", "美国"],
  ["united kingdom", "英国"],
  ["great britain", "英国"],
  ["russian federation", "俄罗斯"],
  ["south korea", "韩国"],
  ["north korea", "朝鲜"],
  ["new zealand", "新西兰"],
  ["south africa", "南非"],
  ["saudi arabia", "沙特阿拉伯"],
  ["united arab emirates", "阿联酋"],
  ["czech republic", "捷克"],
  ["dominican republic", "多米尼加"],
  ["bosnia and herzegovina", "波黑"],
  ["north macedonia", "北马其顿"],
  ["taiwan, province of china", "台湾省"],
  ["taiwan province of china", "台湾省"],
  ["taiwan", "台湾省"],
  ["italy", "意大利"],
  ["italia", "意大利"],
  ["france", "法国"],
  ["germany", "德国"],
  ["deutschland", "德国"],
  ["spain", "西班牙"],
  ["portugal", "葡萄牙"],
  ["netherlands", "荷兰"],
  ["holland", "荷兰"],
  ["belgium", "比利时"],
  ["switzerland", "瑞士"],
  ["austria", "奥地利"],
  ["poland", "波兰"],
  ["sweden", "瑞典"],
  ["norway", "挪威"],
  ["denmark", "丹麦"],
  ["finland", "芬兰"],
  ["ireland", "爱尔兰"],
  ["greece", "希腊"],
  ["turkey", "土耳其"],
  ["türkiye", "土耳其"],
  ["ukraine", "乌克兰"],
  ["romania", "罗马尼亚"],
  ["hungary", "匈牙利"],
  ["bulgaria", "保加利亚"],
  ["serbia", "塞尔维亚"],
  ["croatia", "克罗地亚"],
  ["slovakia", "斯洛伐克"],
  ["slovenia", "斯洛文尼亚"],
  ["lithuania", "立陶宛"],
  ["latvia", "拉脱维亚"],
  ["estonia", "爱沙尼亚"],
  ["luxembourg", "卢森堡"],
  ["iceland", "冰岛"],
  ["malta", "马耳他"],
  ["cyprus", "塞浦路斯"],
  ["israel", "以色列"],
  ["palestine", "巴勒斯坦"],
  ["jordan", "约旦"],
  ["lebanon", "黎巴嫩"],
  ["syria", "叙利亚"],
  ["iraq", "伊拉克"],
  ["iran", "伊朗"],
  ["pakistan", "巴基斯坦"],
  ["india", "印度"],
  ["bangladesh", "孟加拉国"],
  ["sri lanka", "斯里兰卡"],
  ["nepal", "尼泊尔"],
  ["myanmar", "缅甸"],
  ["thailand", "泰国"],
  ["vietnam", "越南"],
  ["cambodia", "柬埔寨"],
  ["laos", "老挝"],
  ["malaysia", "马来西亚"],
  ["singapore", "新加坡"],
  ["indonesia", "印度尼西亚"],
  ["philippines", "菲律宾"],
  ["japan", "日本"],
  ["mongolia", "蒙古"],
  ["china", "中国"],
  ["macao", "中国澳门"],
  ["macau", "中国澳门"],
  ["australia", "澳大利亚"],
  ["canada", "加拿大"],
  ["mexico", "墨西哥"],
  ["brazil", "巴西"],
  ["argentina", "阿根廷"],
  ["chile", "智利"],
  ["colombia", "哥伦比亚"],
  ["peru", "秘鲁"],
  ["venezuela", "委内瑞拉"],
  ["egypt", "埃及"],
  ["nigeria", "尼日利亚"],
  ["kenya", "肯尼亚"],
  ["morocco", "摩洛哥"],
  ["algeria", "阿尔及利亚"],
  ["south sudan", "南苏丹"],
  ["sudan", "苏丹"],
  ["ethiopia", "埃塞俄比亚"],
  ["tanzania", "坦桑尼亚"],
  ["uganda", "乌干达"],
  ["ghana", "加纳"],
  ["qatar", "卡塔尔"],
  ["kuwait", "科威特"],
  ["bahrain", "巴林"],
  ["oman", "阿曼"],
  ["yemen", "也门"],
  ["afghanistan", "阿富汗"],
  ["kazakhstan", "哈萨克斯坦"],
  ["uzbekistan", "乌兹别克斯坦"],
  ["georgia", "格鲁吉亚"],
  ["armenia", "亚美尼亚"],
  ["azerbaijan", "阿塞拜疆"],
  ["belarus", "白俄罗斯"],
  ["moldova", "摩尔多瓦"],
  ["albania", "阿尔巴尼亚"],
  ["north america", "北美洲"],
  ["south america", "南美洲"],
  ["europe", "欧洲"],
  ["asia", "亚洲"],
  ["africa", "非洲"],
  ["oceania", "大洋洲"],
  ["antarctica", "南极洲"]
];

function translateEnglishCountryPhrases(s) {
  let out = String(s);
  for (const [en, zh] of EN_COUNTRY_OR_REGION_TO_ZH) {
    if (!zh) continue;
    const esc = en.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const re = new RegExp(esc, "gi");
    out = out.replace(re, zh);
  }
  return out;
}

module.exports = { translateEnglishCountryPhrases, EN_COUNTRY_OR_REGION_TO_ZH };
